export const OPEN_PROFILE_EDITION = "OPEN_PROFILE_EDITION";

export const CLOSE_PROFILE_EDITION = "CLOSE_PROFILE_EDITION";

export const OPEN_CREATE_EVENT_MODAL = "OPEN_CREATE_EVENT_MODAL";

export const CLOSE_CREATE_EVENT_MODAL = "CLOSE_CREATE_EVENT_MODAL";

export const OPEN_EVENT_VIEW = "OPEN_EVENT_VIEW";

export const CLOSE_EVENT_VIEW = "CLOSE_EVENT_VIEW";

export const UPDATE_EVENT = "UPDATE_EVENT";
