export const OPEN_PROFILE_EDITION = "OPEN_PROFILE_EDITION";

export const CLOSE_PROFILE_EDITION = "CLOSE_PROFILE_EDITION";

export const OPEN_EVENT_VIEW = "OPEN_EVENT_VIEW";

export const CLOSE_EVENT_VIEW = "CLOSE_EVENT_VIEW";
